name: build and test
on:
  push:
    branches: [master]
  pull_request:

jobs:
  mac:
    strategy:
      matrix:
        xcode_version: ["11.2"]
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v1
      - run: |
          swift test --enable-code-coverage
          xcrun llvm-cov export -format=lcov -ignore-filename-regex="Tests/*" -instr-profile .build/x86_64-apple-macosx/debug/codecov/default.profdata ./.build/x86_64-apple-macosx/debug/AlchemyPackageTests.xctest/Contents/MacOS/AlchemyPackageTests > .build/lcov.info
          bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -f .build/lcov.info

  linux:
    strategy:
      matrix:
        swift_version: ["5.1"]
    runs-on: ubuntu-18.04
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test
